### ISSUE TITLE
[ISSUE] State of entity lost when HA restart

### ISSUE THREAD

**Issue by zoic21** [coltondick/ansible_playbook_monitor#2]
Hello,

Like I said on my previous issue thanks for your works it's help me to remove mqtt and use direct integration. I have just an issue it's lost state of entity when home assistant restart. I known home assistant did not handle well that on restart but I thinks it's possible to keep value (I don't known how but I'am pretty sure some integration do that).

Thanks in advance if you can add this.

**Comment by coltondick** [comment]
This issue has been resolved in **release v1.0.0**. 🎉

Please refer to the [release notes](https://github.com/coltondick/ansible_playbook_monitor/releases/tag/v1.0.0) for detailed information on the updates and improvements.

Feel free to test the latest version and share your feedback!

**Comment by zoic21** [comment]
Hello

A big thanks it's perfectly work !!!!!!
